2014-12-02 14:22:50,913 - ERROR :
 Assertion error: Field does not exist in shapefile.
Field: 
Shapefile: basinMask.shp
  fields: ['Id']
Traceback (most recent call last):
  File "waterapputils.py", line 148, in main
    wateruse_processing.apply_wateruse(settings = user_settings.settings)
  File "c:\Users\jlant\jeremiah\projects\python-projects\waterapputils\waterapputils\wateruse_processing.py", line 133, in apply_wateruse
    intersecting_centroids_all = spatialvectors.get_intersected_field_values(intersector = basin_shapefile, intersectee = centroids_shapefile, intersectee_field = settings["wateruse_centroids_shapefile_id_field"], intersector_field = settings["basin_shapefile_id_field"])
  File "c:\Users\jlant\jeremiah\projects\python-projects\waterapputils\waterapputils\spatialvectors.py", line 222, in get_intersected_field_values
    "Field does not exist in shapefile.\nField: {}\nShapefile: {}\n  fields: {}".format(intersector_field, intersector_data["name"], intersector_data["fields"])
AssertionError: Field does not exist in shapefile.
Field: 
Shapefile: basinMask.shp
  fields: ['Id']
